query GetProductDetails($id: ID!) {
    product(id: $id) {
        id
        title
        description
        handle
        productType
        vendor
        tags
        priceRangeV2 {
            minVariantPrice {
                amount
                currencyCode
            }
            maxVariantPrice {
                amount
                currencyCode
            }
        }
        images(first: 10) {
            edges {
                node {
                    url
                    altText
                }
            }
        }
        variants(first: 10) {
            edges {
                node {
                    id
                    title
                    price
                    availableForSale
                }
            }
        }
    }
}
