query GetProductsInCollection($id: ID!, $first: Int = 50) {
  collection(id: $id) {
    id
    title
    products(first: $first) {
      edges {
        node {
          id
          title
          productType
          priceRangeV2 {
            minVariantPrice {
              amount
              currencyCode
            }
          }
          images(first: 1) {
            edges {
              node {
                url
              }
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
